### ISSUE TITLE
Distribute to flathub

### ISSUE THREAD

**Issue by hrzlgnm** [hrzlgnm/mdns-browser#207]
https://v2.tauri.app/distribute/flatpak/

**Comment by jing2uo** [comment]
Hi @hrzlgnm — thanks for mdns-browser, it's become my go-to for looking at what's advertising itself on a network.

I maintain [FlatPark](https://github.com/flatpark/flatpark), a small hub that provides Flatpak installs for desktop apps that don't have one yet, and I've packaged mdns-browser there, so the option exists for people who want it with no work on your side.

It uses Flatpak **extra-data**, so it downloads your official `mdns-browser_<version>_amd64.deb` unmodified at install time and tracks new releases automatically from your GitHub releases — I don't rehost or patch anything.

Install:

```
flatpak remote-add --if-not-exists flatpark https://dl.flatpark.org/flatpark.flatpakrepo
flatpak install flatpark io.github.hrzlgnm.mdns-browser
```

App page: https://flatpark.org/apps/io.github.hrzlgnm.mdns-browser

Three notes on how the package is configured, in case they're ever useful to you:

- `--share=network` is sufficient for discovery. It puts the app in the host network namespace, so multicast on 224.0.0.251:5353 reaches it normally; no extra capability is needed.
- The package needs no filesystem access at all, so it ships with none.
- While writing the update resolver I noticed the release tags moved from `mdns-browser-v1.9.19` to `v1.15.0`, so I read the asset URL from the release's asset list rather than composing it from the tag. Mentioning it only in case it matters for anything else consuming your releases.

I've only smoke-tested it myself — it installs, launches and renders correctly with no missing libraries — but I have not confirmed that services actually populate the list on a real LAN, so my coverage is certainly incomplete. If you have time to put it through real use and see what breaks, I'd genuinely appreciate it, and any issue or PR on the packaging is very welcome.

If you'd be willing to make FlatPark an officially supported install method — recommending it in your README, docs or download page — I would be very grateful. It takes the Flatpak packaging and distribution work off your plate while giving your users a clean install and automatic updates.

And if you'd rather I not distribute it, just say so and I'll take it down right away, no questions asked. If you're happy for it to stay, I'll add a blue "developer-approved" shield to its FlatPark page and feature it on the homepage.
